#!/bin/bash

https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/accelerated-jk.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/align-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/alpha.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/calendar-vim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/ccc-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/chezmoi-vim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/clock-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/comment-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/copilot.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/crates-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/csvlens-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/denops-docker-vim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/denops.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/dial-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/dotfyle-metadata.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/dps-translate-vim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/dressing-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/eskk-vim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/fern.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/fidget.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/git-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/gitsigns-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/glow-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/hawtkeys-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/human-rights.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/image-preview-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/kdl.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/kensaku-command.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/kensaku-search.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/live-server-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/lualine.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/luasnip.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/mason-null-ls.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/mason.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/mastodon-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/migemo-search-vim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/mkdir-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/neoscroll-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/noice.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/none-ls.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/nvim-2048.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/nvim-autopairs.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/nvim-cmp.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/nvim-hlslens.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/nvim-lspconfig.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/nvim-scrollbar.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/nvim-silicon.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/nvim-surround.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/obsidian-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/orgmode.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/pandoc-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/pantran-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/ron.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/skkeleton.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/smoothcursor-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/telescope-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/template-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/themery-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/themes.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/todo-comments.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/tree-sitter.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/trouble.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/typos-nvim.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vim-ambiwidth.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vim-cargo-make.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vim-just.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vim-kitty.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vim-markdown.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vim-quickrun.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vim-scouter.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vim-startuptime.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/vimdoc-ja.lua
https://raw.githubusercontent.com/mimikun/dotfiles/master/dot_config/nvim/lua/plugins/which-key.lua
